### ISSUE TITLE
gcc 8.3.0 linking problem with std::filesystem 

### ISSUE THREAD

**Issue by denisbertini** [gemfony/geneva#1]
**Describe the bug**
compiling develop branch with gcc 8.3.0 leads to std::filesystem linking problem

**To Reproduce**
try compiling develop branch with gcc 8.3.0

**Expected behavior**
the project should compile  

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux Centos7

**Additional context**
Linking error message may be to non full c++ 17 compliance of gcc 8.3.0, (  compiles with gcc 9.3 without errors  )

```
In function `g_error_streamer::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const':
GenevaStandardTests.cpp:(.text._ZNK16g_error_streamercvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv[_ZNK16g_error_streamercvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv]+0xa8): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
../../../src/common/libgemfony-common.so.1.10.0: undefined reference to `std::filesystem::__cxx11::path::remove_filename()'
../../../src/common/libgemfony-common.so.1.10.0: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
../../../src/geneva/libgemfony-geneva.so.1.10.0: undefined reference to `std::filesystem::last_write_time(std::filesystem::__cxx11::path const&)'
../../../src/geneva/libgemfony-geneva.so.1.10.0: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
../../../src/geneva/libgemfony-geneva.so.1.10.0: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
../../../src/geneva-individuals/libgemfony-geneva-individuals.so.1.10.0: undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
../../../src/geneva-individuals/libgemfony-geneva-individuals.so.1.10.0: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
../../../src/geneva/libgemfony-geneva.so.1.10.0: undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'
../../../src/common/libgemfony-common.so.1.10.0: undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
../../../src/geneva/libgemfony-geneva.so.1.10.0: undefined reference to `std::filesystem::rename(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)'
```

**Comment by denisbertini** [comment]
If one do not use gcc 9,  it is required to link explicitely with 
stdc++fs
Adding this library in CMake solve the linking issue.

**Comment by agarcia-gmf** [comment]
As reference, "File system library" should be fully supported in GCC from version 8, https://en.cppreference.com/w/cpp/compiler_support (C++17 library features), so it is worth to have this small fix.
